services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-db
    restart: always
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client
    environment:
      CLICKHOUSE_DB: hezzl
      CLICKHOUSE_USER: hezzl_admin
      CLICKHOUSE_PASSWORD: hezzl_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  go:
    build:
      context: .
      target: final
    container_name: go-app-clickhouse-service
    restart: always
    depends_on:
      clickhouse:
        condition: service_healthy
    environment:
      CONFIG_PATH: config/dev.yaml
    command: ["./main", "--config=./config/dev.yaml"]

volumes:
  clickhouse_data:
  clickhouse_logs: