version: "3"

tasks:
  run:
    desc: "Run app"
    cmds:
      - docker compose up -d --build

  down:
    desc: "Shutdown app"
    cmds:
      - docker compose down

  migrate-up:
    desc: "Init database"
    cmds:
      - docker build -f ./Dockerfile-migrate -t my-migrate-image .
        && docker run -e MIGRATION_DIRECTION=up my-migrate-image #--direction=up

  migrate-down:
    desc: "Shutdown database"
    cmds:
      - docker build -f ./Dockerfile-migrate -t my-migrate-image . 
        && docker run -e MIGRATION_DIRECTION=down my-migrate-image
